### ISSUE TITLE
RewindableAllocator explanation 

### ISSUE THREAD

**Issue by botaurus** [bjorn-johansson/Unity-DOTS-Boids#1]
Hey I'm wondering if you could explain a little (like I'm 5) why you used the RewindableAllocator instead of Allocator.TempJob in BoidSystem.cs? I'm reading about the RewindableAllocator and its a bit over my head
thank you  @bjorn-johansson

**Comment by botaurus** [comment]
after a little more digging I found this: 
https://docs.unity3d.com/Packages/com.unity.entities@1.0/manual/allocators-custom-prebuilt.html

**Comment by bjorn-johansson** [comment]
Hello! I've gone down the same rabbit hole, and to be honest I am still not 100 on exactly how the worlds RewindableAllocator works with its memory block rewind feature and how fast it is compared to TempJob, so i cant really speak on this. The main reasons i used it was to avoid having to deallocate it, as well as potential issues with the 4 frames TempJob gives you combined with scheduled jobs that execute over several frames.

The plan for this project has been to revisit it to learn more about optimization techniques and I've been wanting to explore variable update rates for boid direction changes. Big jobs such as the one in BoidSystem.cs can take longer than 4 frames to complete, which means that if TempJob is used it will cause memory leaks.

World.UpdateAllocator also gets rewound every World update and invalidates the NativeArray, which means theres no need to asynchronously deallocate it like with TempJob, which just means less hassle.

It does bug me a little bit that the unity manuals link to rewindable allocators leads nowhere as I've been really wanting to learn more about exactly how they work.

**Comment by botaurus** [comment]
ah, thanks for the reply! And thank you for the project, been reading through it and I've found it helpful.
